apiVersion: v1
data:
  config.yaml: |
    service:
      name: blueprint-greeting-dev
      rest: 8080
      health: 8081
      logLevel: debug
kind: ConfigMap
metadata:
  name: config
  namespace: default
