apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: greeting-hpa-memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: greeting-deployment
  minReplicas: 1 
  maxReplicas: 2
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: AverageValue 
        averageValue: 500Mi 
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Max
