apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: greeting-hpa-memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: greeting-deployment
  minReplicas: 1 
  maxReplicas: 10 

