apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-probe-deployment
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: localhost:5003/development/service-greeting:latest
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: config
