apiVersion: v1
kind: Pod
metadata:
  name: greeting-pod
spec:
  containers:
    - name: greeting1
      image: localhost:5003/development/service-greeting:latest
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: config
